[package]
name = "wrecked_bindings"
version = "0.1.0"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
edition = "2018"
description = "Bindings for the wrecked terminal graphics library"

[dependencies]
wrecked = { path = "/home/pent/Projects/wrecked/" }

[lib]
name = "wrecked_bindings"
crate-type = ["dylib"]

