[package]
name = "wrecked"
version = "0.1.0"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
edition = "2018"
description = "A terminal graphics library"

[dependencies]
terminal_size = { git = "https://github.com/eminence/terminal-size.git" }
termios = "0.3"

[lib]
name = "wrecked"
crate-type = ["dylib"]

