[package]
name = "wrecked"
version = "0.1.0"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
edition = "2018"
description = "A terminal graphics library"

[dependencies]
termios = "0.3"
libc = "0.2"

[lib]
name = "wrecked"
crate-type = ["dylib"]

