[package]
name = "wrecked_bindings"
version = "0.1.1"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
edition = "2018"
description = "Bindings for the wrecked terminal graphics library"

[dependencies]
wrecked = { git = "https://github.com/quintinfsmith/wrecked" }

[lib]
name = "wrecked_bindings"
crate-type = ["cdylib"]

