[package]
name = "wrecked_bindings"
version = "0.2.12"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
edition = "2018"
description = "Bindings for the wrecked terminal graphics library"

[dependencies]
wrecked = "^0.1.22"

[lib]
name = "wrecked_bindings"
crate-type = ["cdylib"]

