[package]
name = "wrecked_bindings"
version = "1.0.11"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
edition = "2018"
description = "Bindings for the wrecked terminal graphics library"

[dependencies]
wrecked = "^1.0.8"

[lib]
name = "wrecked_bindings"
crate-type = ["cdylib"]

